config/routes.rb
Rails.application.routes.draw do
root to: "homes#top" 
resources "books"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end 

  def edit
    @book = Book.find(params[:id])
  end

  def update 
    @book = Book.find(params[:id])
    if@book.update(book_params)
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end 

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/_errors.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% book.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'errors',book: @book %>

<%= form_with model:@book, url:book_path(@book.id), method: :patch do |f|  %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to 'Show',book_path(@book.id) %> | <%= link_to 'Back',books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

  <% @books.each do |book| %>
    <tbody>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show',book_path(book.id) %></td>
        <td><%= link_to 'Edit',edit_book_path(book.id) %></td>
        <td><%= link_to 'Destroy',book_path(book.id),method: :delete %></td>
      </tr>
    </tbody>
  <% end %>
</table>


<h2>New book</h2>

<%= render 'errors',book: @book %>

<%= form_with model:@book, url:books_path ,method: :post  do |f| %>
  <div class= "title_area">
    <div><%= f.label :title %></div>
    <%= f.text_field :title %>
  </div>

  <div class= "body_area">
    <div><%= f.label :body %></div>
    <%= f.text_area :body %>
  </div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %></p>
<%= link_to 'Edit',edit_book_path %> | <%= link_to 'Back',books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookersへ!</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<%= link_to 'start',books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>